name: Simple LS

on:
  workflow_dispatch:   # 手動実行できる
  push:                # push 時にも実行したいなら残す

jobs:
  run-ls:
    runs-on: ubuntu-latest   # GitHub 提供のクラウドランナー
    steps:
      - uses: actions/checkout@v4
      - name: Run ls
        run: ls -al
